### ISSUE TITLE
Change maintainer / repo location

### ISSUE THREAD

**Issue by sfirke** [mattroumaya/surveymonkey#101]
@mattroumaya has stepped up and taken ownership of this package for over a year now.  I propose that it would be an improved state of affairs all around if he were to become the maintainer of this project, being listed as the first author in the DESCRIPTION file and moving the repo to github.com/mattroumaya/surveymonkey.  The README can be updated to note that the package was initially developed by TNTP and has since been maintained and enhanced by Matt.

Any objections or considerations?  I'll leave this open for a week or two and then if none surface, I believe I still have the privileges to initiate a transfer of the repo to his account.

**Comment by mattroumaya** [comment]
Sounds good @sfirke! I'm on GH pretty much all day so feel free to ping me here, or at matthewroumaya@gmail.com

**Comment by sfirke** [comment]
@mattroumaya I think you need to delete mattroumaya/surveymonkey for this to work, right now the transfer errors with:
 >mattroumaya/surveymonkey already exists and You can only transfer a repository from an organization to yourself at this time 

I'll look into the second part of that error.

**Comment by mattroumaya** [comment]
@sfirke I just deleted my fork so that part should be taken care of

**Comment by sfirke** [comment]
Voila!  And this works too now: https://mattroumaya.github.io/surveymonkey/  I think if you knit README.Rmd and push this is all set.

Thank you for taking over stewardship of this package!

**Comment by mattroumaya** [comment]
Thank you for being open to collaboration and trusting me with this, @sfirke! 

Contributing to this package was my first experience with opensource and I've learned a ton over the past year or so. I'll do my best to keep it up and running smoothly, and maybe even get it on CRAN some day! Thanks for all of the work you've put into developing it! 🎉
