### ISSUE TITLE
Why does the package depend on R >=3.4?

### ISSUE THREAD

**Issue by sfirke** [mattroumaya/surveymonkey#52]
I apparently changed this from 3.4.3 to 3.4.0 in Dec '19, but don't remember why.

Commit where I changed it: https://github.com/tntp/surveymonkey/commit/b33417d1e0a71123e17a5a5c6542e65dd072867f

**Comment by sfirke** [comment]
Now it depends on >= 3.5.0 because of changes to `loadRDS` and `readRDS` versions 3, I'm using those to create objects for testing.  Use older versions to not require 3.5.0+ ? Not a top priority.

**Comment by mattroumaya** [comment]
Closing because this seems to be working fine and we are now well beyond 3.5.0
