### ISSUE TITLE
Update documentation about API access/account types

### ISSUE THREAD

**Issue by mattroumaya** [mattroumaya/surveymonkey#99]
I changed jobs somewhat recently and am able to access many of the API endpoints using an entirely free account. More info on scopes available to free users [here](https://developer.surveymonkey.com/api/v3/#scopes). 

Tagging @sfirke in case you are at all interested in checking this out. 

If anyone has more insight about the specifics API access between types of free/enterprise accounts, definitely feel free to comment or put in a PR to update documentation.

**Comment by sfirke** [comment]
Whoa that's great!  I just looked at the doc you linked and agree that it looks like the package should work for users with free accounts.  Maybe change the README to say it should work for free users but please file an issue to confirm or deny that's the case?
